#!/usr/bin/env python3
"""
The MIT License (MIT)

Copyright (c) 2017 Stefan Graupner

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import sys
from src.validator import Validator
from colorama import init
from optparse import OptionParser
import argparse


def init_validator(endpoint, options):
    validator = Validator(url=endpoint, options=options)
    validator.validate()


def main():
    parser = argparse.ArgumentParser(prog='validate')

    parser.add_argument(
        '--no-redis',
        help='disable redis based caching',
        action='store_false',
        dest='redis',
        default=True
    )

    parser.add_argument(
        "--porcelain",
        help="disable colored output",
        default=False,
        action="store_true"
    )

    parser.add_argument(
        "--silent",
        help="disable CLI output",
        default=False,
        action="store_true",
        dest="silent"
    )

    parser.add_argument(
        "-s",
        "--validate-schema",
        help="additionally validate each object against the json schema (This WILL take longer)",
        default=False,
        action="store_true",
        dest="validate_schema"
    )

    parser.add_argument(
        "-v",
        help="configure the output verbosity (this is only relevant for direct cli usage, writing to file will always output everything)",
        dest="verbosity",
        action="count",
        default=0,
    )

    parser.add_argument(
        "-o",
        help='configure the output file',
        dest="output",
        action="store",
        default="validation-result.json"
    )

    parser.add_argument(
        'oparl_endpoint',
        nargs='+'
    )

    args = parser.parse_args()

    if args.verbosity > 3:
        print("You cannot possibly make me embarrass myself that much.")
        exit()

    # init colorama
    init(strip=args.porcelain, autoreset=True)

    if type(args.oparl_endpoint) == list:
        for endpoint in args.oparl_endpoint:
            init_validator(endpoint, args)
    else:
        init_validator(endpoint, args)


if __name__ == "__main__":
    main()
