#!/usr/bin/env python3
import sys
from src.Validator import Validator

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage:\n\tvalidate OParl_Endpoint")
        exit()

    validator = Validator(sys.argv[1])
