#!/usr/bin/env python3
# The MIT License (MIT)
#
# Copyright (c) 2017 Stefan Graupner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys
from src.validator import Validator
from colorama import init
from optparse import OptionParser

if __name__ == "__main__":
    # TODO: switch over to argparse as optparse is deprecated
    parser = OptionParser()

    parser.add_option("-r", "--redis", help="Disable redis based caching", default=True, action="store_false")
    parser.add_option("-p", "--porcelain", help="Disable colored output", default=False, action="store_true")
    parser.add_option("-l", "--log-output", help="Store the validation output in a log file", default=False, action="store_true", dest="save_results")

    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.print_help()
        exit()

    # init colorama
    init(strip=options.porcelain, autoreset=True)

    validator = Validator(url=args[0], options=options)
    validator.validate()
